dist: bionic
language: python

env:
  global:
    # Doctr deploy key for pydata/pandas-datareader
    - secure: "iGbOAbBSV5y0TKDh2CifRSk6OpLA9GbEEL/hscHFLSDDUCWcdfvYXda3SWJFWyoQ5QUxSigXWd+ukr4u92d7lmB7m3TWj6BAMNuRpatTgnejLNwLvNeYdvLAxPvx39Cq85frd1Rx1beBLn3h/4wm4Ah+dR5W9NH8+x3OuZMH3Eo="

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: PANDAS=0.24 NUMPY=1.16
  - python: 3.5
    env: PANDAS=0.21 NUMPY=1.13
  - python: 3.5
    env: PANDAS=0.22 NUMPY=1.13
  - python: 3.6
    env: PANDAS=0.23 NUMPY=1.14
  - python: 3.7
    env: PANDAS=0.25 NUMPY=1.17 DOCBUILD=true
  # In allow failures
  - env: PYTHON=3.7 PANDAS="MASTER"
  allow_failures:
    - env: PYTHON=3.7 PANDAS="MASTER"

install:
  - source ci/pypi-install.sh;
  - pip install codecov coveralls beautifulsoup4 flake8
  - pip list
  - python setup.py install

script:
    - pytest -s -r xX --cov-config .coveragerc --cov=pandas_datareader --cov-report xml:/tmp/cov-datareader.xml --junitxml=/tmp/datareader.xml
    - flake8 --version
    - flake8 pandas_datareader

after_script:
  - |
    if [[ "$DOCBUILD" ]]; then
      cd docs
      make html && make html
      cd ..
      doctr deploy devel --build-tags
      if [[ -z "$TRAVIS_TAG" ]]; then
        echo "Not a tagged build."
      else
        doctr deploy stable --build-tags
      fi
    fi
  - coveralls
  - codecov
